#blinkit customer details.
customer_id=int(input("Enter customer Id:"))
customer_name=input("Enter customer Name: ")
customer_Wallet=float(input("Enter customer Wallet: "))
customer_cart_items=input("Enter cart items: ").split()
available_coupons=int(input("Enter Number of Available coupons: ").split())
customer_free_cash=float(input("Enter the free cash: "))
discount_details=(available_coupons,customer_free_cash)
customer_Wishlist=set(input("Enter the Wishlist: ").split())
customer_order_history=input("Enter order history: ").split()
customer_Address=input("Enter the delivery Address: ")
customer_GST_details=input("Enter the GST details: ")
customer_details={'Name':customer_name,'Address':customer_Address}
print(f"customer id is: {customer_id}")
print(f"customer name is: {customer_name}")
print(f"customer Wallet is: {customer_Wallet}")
print(f"customer cart_items: {customer_cart_items}")
print(f"available coupons is: {available_coupons }")
print(f"customer_free_cash is: {customer_free_cash}")
print(f"customer_Wishlist is: {customer_Wishlist}")
print(f"customer_order_history is: {customer_order_history}")
print(f"customer_Addressis: {customer_Address}")
print(f"customer_GST_details is: {customer_GST_details}") 